apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventario-app
      version: green
  template:
    metadata:
      labels:
        app: inventario-app
        version: green
    spec:
      containers:
      - name: inventario-app
        image: ghcr.io/caromml55-maker/examenfinalsd:latest
        imagePullPolicy: Always
        env:
        - name: APP_VERSION
          value: "v2"
        - name: APP_COLOR
          value: "green"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
